### PR TITLE
feat: Change default filter on Dashboard from 'All Incidents' to 'Pending'

### PR DESCRIPTION
**Pull request by peterpaints**
#### What does this PR do?
- Changes the default filter on Dashboard from `All Incidents` to `Pending`.
- **See screenshots section**
- One can change the filter to other incident categories, for instance `In Progress`
- The styling has been coded to resemble Humphrey's designs as closely as possible.
#### Where should the reviewer start?
- View file changes on PR
#### How should this be manually tested?
- Fire the app up on localhost, and navigate to login. You'll redirect to /dashboard.
#### Screenshots (if appropriate)
screen shot 2018-06-23 at 00 52 20
screen shot 2018-06-23 at 00 52 49
screen shot 2018-06-23 at 00 53 07

### CODE REVIEW

**Comment by kimobrian** [comment]
@peterpaints Just a quick change. Can you make the heading static when I scroll. Like keep the headings out of the scrolling section. So the incidents can scroll up and down but the headings should not.

**Comment by peterpaints** [comment]
@kimobrian To clarify, that's when the incidents are filtered to `All Incidents`, right? You want the `PENDING` heading and its `underline`, for instance, to be fixed?

**Comment by kimobrian** [comment]
@peterpaints Exactly

**Comment by peterpaints** [comment]
@kimobrian Sawa. On it.

**Pull request merged**
