### PR TITLE
Refactor unit tests to single test file per component

### PR DESCRIPTION
**Pull request by theartisancodes**
#### What does this PR do?
- Move the tests from a single directory to single file per component
#### Where should the reviewer start?
[Place link to file here]()
#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[162381159](https://www.pivotaltracker.com/n/projects/2117172/stories/162381159)
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by cosmas28** [comment]
What do you think about ignoring the snapshot files?

**Comment by theartisancodes** [comment]
> What do you think about ignoring the snapshot files?

@cosmas28 I think its good for it to be committed alongside code changes and reviewed as part of the tests. Or what do you have in mind about it?

**Comment by cosmas28** [comment]
@nzaujk I think it's not good practice to commit the snapshot files because they will create unnecessary conflicts when others make changes to the components.

**Comment by andela-oakinseye** [comment]
@cosmas28 @nzaujk
Is that not exactly what snapshots are supposed to do? You can always regenerate them when you make changes to the components.

**Review by andela-oakinseye — APPROVED** [review]

**Pull request merged**
