### PR TITLE
#163856971 Fix bug to view incident details, notes and chats

### PR DESCRIPTION
**Pull request by ronaldndirangu**
#### What does this PR do?
- Ensures a user can view incident details, notes and chats.

#### Description of Task to be completed?
- Fix bug with viewing an incidents details, notes and chats.

#### Where should the reviewer start?
- View the changed files in the PR.

#### How should this be manually tested?
- Clone the frontend repo `https://github.com/AndelaOSP/wire.git`.
- Clone the backend repo `https://github.com/AndelaOSP/wire-api.git`
- cd into the `wire-api/src` directory and start the server by running `$ yarn start:dev`
- cd into the `wire` directory and run `$ yarn start`
- Log in to the application.
- Click on one reported incident.
- You should be redirected to the view incident details, notes and chats page.

#### Any background context you want to provide?
- On clicking the incident the user would be redirected to a blank page

#### What are the relevant pivotal tracker stories?
[#163856971](https://www.pivotaltracker.com/story/show/163856971)

#### Screenshots (if appropriate)
screenshot 2019-02-11 at 14 17 50

### CODE REVIEW

**Comment by munyili-samuel** [comment]
Good work @ronaldndirangu, Works as expected!
Not sure whether this is part of the task though, would you mind changing the font for the notes page to be consistent with the rest of the app?
Currently, it is `Times`

**Comment by ronaldndirangu** [comment]
Currently, the font is `DINPro` Where exactly is the font `Times`? @munyili-samuel

**Review by kisakyegordon — APPROVED** [review]
lgtm

**Review by munyili-samuel — APPROVED** [review]
LGTM

**Pull request merged**
