### PR TITLE
fix change of assignee in sidebar clearing reporter information

### PR DESCRIPTION
**Pull request by LordRahl90**
#### What does this PR do?

Fixes the bug that makes the reporter's name clear off once an assignee has been selected.
#### Description of Task to be completed?

As an admin, I should be able to assign a user to an incident, currently, this clears out the name of the reporter on the timeline.

#### Where should the reviewer start?
N/A
#### How should this be manually tested?
* Clone this project.
* Checkout `bg-persist-reporter-record-on-ui`
* Log into the dashboard as an admin
* Select a single incident to view the incident details.
* Change the assignee, then confirm that the reporter's details doesn't change.

#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
N/A
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by TheSteelGuy** [comment]
Kindly ensure you squash these commits, ensure you have a story on the pt board and change your branch name to the accepted format, check other branches to see the pattern. Your Pr title also does not look right. Kindly care to add some light why this many file changes for this task?

The file changed much mostly because of the mode. sincerely, I do not understand myself. any insight to this will be appreciated, mostly to prevent future occurrence.

**Review by Paulvitalis200 — COMMENTED** [review]
The bug has been fixed and the feature works well. However, kindly squash your commits and fix the merge conflicts for me to approve.

**Comment by LordRahl90** [comment]
> The bug has been fixed and the feature works well. However, kindly squash your commits and fix the merge conflicts for me to approve.

Merge conflicts has be solved.
However squashing all the commits to 1 has been a tough job.

**Review by billkabanga — COMMENTED** [review]
Great work on the PR. I would like to also request that you add the related pivotal tracker story and a link to the PT board. It would also be appreciable if you add GIFs to show before and after of the feature. This will make it easier and better to get a thorough review.

**Pull request closed without merging**
