### PR TITLE
#156320151 Test for login component

### PR DESCRIPTION
**Pull request by emmabaye**
#### What does this PR do?
Test Login component and raise the coverage to minimum 85%
#### Description of Task to be completed?
N/A
#### Where should the reviewer start?
[LoginPage.test.jsx](https://github.com/AndelaOSP/wire/blob/1b3fb2b21ddd26d2d5b9a53a0e52a4942117c188/src/pages/Login/LoginPage.test.jsx)
#### How should this be manually tested?
Run test with comment `npm run test:fend` 
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#156320151](https://www.pivotaltracker.com/story/show/156320151)
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Review by theartisancodes — APPROVED** [review]

**Comment by theartisancodes** [comment]
could you address the errors on the PR? @emmabaye

**Comment by theartisancodes** [comment]
The branch needs to be updated

**Comment by emmabaye** [comment]
> could you address the errors on the PR? @emmabaye

I have addressed the errors.

**Comment by emmabaye** [comment]
> The branch needs to be updated

I have updated the branch.

**Pull request merged**
